version: '3.8'

services:

  api:
    container_name: nest_api
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
      
  database:
    image: postgres
    container_name: nest_db
    environment:
      POSTGRES_DB: nest_js
      POSTGRES_USER: mmtec
      POSTGRES_PASSWORD: 36257
    ports:
      - "5433:5433"